@startuml History_Monitor_Greenhouse

actor Employee
participant CNT_GM_Web
participant CNT_GM_WebApi
participant CNT_GM_DB
participant CNT_GM_WebRTCServer
participant CNT_GM_Secrets
participant CNT_VideoCamera
participant CNT_GM_Redis_DB

skinparam SequenceMessageAlignment center

autonumber 1
group Получить список теплиц
    Employee -> CNT_GM_Web: web, открытие формы со списком теплиц
    CNT_GM_Web -> CNT_GM_WebApi: REST, получить список теблиц \n GET:\api\v1\organisations\{id}\greenhouses
    CNT_GM_WebApi -> CNT_GM_DB: sql, получить спикок теплиц в организации
    CNT_GM_DB --> CNT_GM_WebApi: tcp, список теплиц
    CNT_GM_WebApi --> CNT_GM_Web: HTTP 200, json:GreenhousesDTO
    CNT_GM_Web --> Employee: web, отобразить перечень теплиц
end
group Получить список видеокамер в теблице
    Employee -> CNT_GM_Web: web, открытие карточки теплицы
    CNT_GM_Web -> CNT_GM_WebApi: REST, получить список видеокамер в теплице \n GET:\api\v1\greenhouses\{id}\video-cameras
    CNT_GM_WebApi -> CNT_GM_DB: sql, получить спикок видеокамер
    CNT_GM_DB --> CNT_GM_WebApi: tcp, список теплиц видеокамер в  теплице
    CNT_GM_WebApi --> CNT_GM_Web: HTTP 200, json:VideoCamerasDTO
    CNT_GM_Web --> Employee: web, отобразить перечень камер в теблице
end
group Анализ данных по датчикам
    Employee -> CNT_GM_Web: web, набирает произвольные арифметико-логические выражения для анализа
    CNT_GM_Web -> CNT_GM_WebApi: HTTP, GraphQL: \api\v1\sensor-analytics
    CNT_GM_WebApi -> CNT_GM_TimeSeries_DB: 8443/TCP, получить данные
    CNT_GM_TimeSeries_DB --> CNT_GM_WebApi:  8443/TCP, данные по датчикам
    CNT_GM_WebApi --> CNT_GM_Web: HTTP, GraphQL, данные податчикам
    CNT_GM_Web --> Employee: web, отображение данных по датчикам
end
group Получить видео с камер по заданным критерия
    Employee -> CNT_GM_Web: web, указывает параметры для запроса данных с камеры
    CNT_GM_Web -> CNT_GM_WebRTCServer: websocket, инициализация получения видео с выбранной камеры \n GET:\api\v1\video-cameras\{id}\video\archive?{time_begin}&{time_end}
    CNT_GM_WebRTCServer -> CNT_GM_Secrets: 8200/TCP, получить секреты по выбранной камере
    CNT_GM_Secrets --> CNT_GM_WebRTCServer: 8200/TCP, секреты
    CNT_GM_WebRTCServer -> CNT_VideoCamera: TCP/RTSP, запрос получениz видео
    CNT_VideoCamera -> CNT_GM_WebRTCServer: UDP/RTC, трансляция видео
    CNT_GM_WebRTCServer--> CNT_GM_Web: WebSocet, MSE, трансляция видео
    CNT_GM_Web --> Employee: web, отображение видео работнику
end